INSERT INTO dog (id, name, breed, origin) VALUES (1, 'name1','breed1','origin1');
INSERT INTO dog (id, name, breed, origin) VALUES (2, 'name2','breed2','origin2');
INSERT INTO dog (id, name, breed, origin) VALUES (3, 'name3','breed3','origin3');
INSERT INTO dog (id, name, breed, origin) VALUES (4, 'name4','breed4','origin4');
INSERT INTO dog (id, name, breed, origin) VALUES (5, 'name5','breed5','origin5');
INSERT INTO dog (id, name, breed, origin) VALUES (6, 'Fluffy', 'Pomeranian', 'Mountain View, CA');
INSERT INTO dog (id, name, breed, origin) VALUES (7, 'Spot', 'Pit Bull', 'Austin, TX');
INSERT INTO dog (id, name, breed, origin) VALUES (8, 'Ginger', 'Cocker Spaniel', 'Kansas City, KS');
INSERT INTO dog (id, name, breed, origin) VALUES (9, 'Lady', 'Direwolf', 'The North');
INSERT INTO dog (id, name, breed, origin) VALUES (10, 'Sasha', 'Husky', 'Buffalo, NY');